name: sortree
description: A tree-like data structure that can be used for efficient, persistent, complex sorting.
version: 0.1.0
homepage: https://www.github.com/RSSchermer/sortree.dart
author: R.S. Schermer <roland0507@gmail.com>
documentation:
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  meta: "^1.0.5"
  quiver: "^0.24.0"
dev_dependencies:
  test: ^0.12.0
